3 errors
FirebaseError: Firebase Storage: User does not have permission to access 'collection_images/EmI5k1D9Dng7gNvpJ8t8/Screenshot 2025-06-02 at 10.29.27 am.png'. (storage/unauthorized)

Error: [DEBUG] Error code: "storage/unauthorized"
    at createUnhandledError (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at handleImageUpload (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/src_a4b3ce6e._.js:955:21)

Error: [DEBUG] Error message: "Firebase Storage: User does not have permission to access 'collection_images/EmI5k1D9Dng7gNvpJ8t8/Screenshot 2025-06-02 at 10.29.27 am.png'. (storage/unauthorized)\nForbidden"
    at createUnhandledError (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at handleImageUpload (https://6000-firebase-studio-1748845330401.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev/_next/static/chunks/src_a4b3ce6e._.js:956:21)